"""Wave 4 PR-2 — central-install shim ``VNX_PROJECT_ROOT`` detection.

The shim installed by ``install-central.sh`` at ``~/.vnx-system/bin/vnx`` must,
before exec-ing the pinned ``bin/vnx``, detect the operator's project root and
export it as ``VNX_PROJECT_ROOT`` (the inner resolver prefers it). The detection
contract:

  * walk up from ``$PWD`` for a ``.vnx-version`` (or ``.vnx/config.yml``) pin;
  * STOP at the git boundary — never adopt a pin/root above the repository root,
    so a nested project without its own pin cannot leak onto a parent's;
  * fall back to the git root when no pin is found inside the repo;
  * clear any inherited ``VNX_PROJECT_ROOT`` first so a stale shell export cannot
    survive a ``cd`` into another project.

The real shim is generated by ``install-central.sh`` (clone/verify stubbed out)
and then executed; a stub inner ``bin/vnx`` echoes the env the shim exported.
Nothing about the detection logic is reimplemented in Python.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parent.parent
_SCRIPT = _REPO_ROOT / "install-central.sh"
_VERSION = "v1.0.0-rc4"

_UNSET = "__UNSET__"


def _git_init(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    subprocess.run(["git", "init", "-q"], cwd=path, check=True)
    subprocess.run(["git", "config", "user.email", "t@example.com"], cwd=path, check=True)
    subprocess.run(["git", "config", "user.name", "tester"], cwd=path, check=True)
    subprocess.run(["git", "commit", "-q", "--allow-empty", "-m", "init"], cwd=path, check=True)
    return path.resolve()


def _install_shim(tmp_path: Path) -> Path:
    """Install the real shim into a temp central-install tree; return shim path.

    The inner ``versions/<v>/bin/vnx`` is a stub that prints the env the shim
    exported, so the test observes the actual exported ``VNX_PROJECT_ROOT``.
    """
    target = tmp_path / "vnx-system"
    version_dir = target / "versions" / _VERSION
    inner_bin = version_dir / "bin"
    inner_bin.mkdir(parents=True)
    inner = inner_bin / "vnx"
    inner.write_text(
        "#!/usr/bin/env bash\n"
        'echo "VNX_PROJECT_ROOT=${VNX_PROJECT_ROOT:-' + _UNSET + '}"\n'
        'echo "VNX_HOME=${VNX_HOME}"\n'
        'echo "PWD=${PWD}"\n',
        encoding="utf-8",
    )
    inner.chmod(0o755)

    # Run install-central.sh with clone/verify/prereqs stubbed so only the shim
    # is written (the version dir already exists above).
    body = _SCRIPT.read_text(encoding="utf-8")
    head, sep, _ = body.rpartition('main "$@"')
    assert sep
    program = (
        head
        + "check_prereqs() { :; }\n"
        + "clone_version() { :; }\n"
        + "verify_install() { :; }\n"
        + 'main "$@"\n'
    )
    env = {k: v for k, v in os.environ.items() if not k.startswith("VNX_")}
    res = subprocess.run(
        ["bash", "-c", program, "install-central", "--target", str(target), "--version", _VERSION],
        env=env,
        capture_output=True,
        text=True,
    )
    assert res.returncode == 0, res.stderr
    shim = target / "bin" / "vnx"
    assert shim.is_file() and os.access(shim, os.X_OK)
    return shim


def _run_shim(shim: Path, cwd: Path, extra_env: dict | None = None) -> dict:
    env = {k: v for k, v in os.environ.items() if not k.startswith("VNX_")}
    if extra_env:
        env.update(extra_env)
    res = subprocess.run(
        ["bash", str(shim)],
        cwd=str(cwd),
        env=env,
        capture_output=True,
        text=True,
    )
    assert res.returncode == 0, f"shim failed: {res.stderr}"
    parsed = dict(
        line.split("=", 1) for line in res.stdout.splitlines() if "=" in line
    )
    parsed["_stderr"] = res.stderr
    return parsed


# ── Pin found in a parent dir within the same repo ───────────────────────────
def test_shim_finds_vnx_version_in_parent_dir(tmp_path):
    shim = _install_shim(tmp_path)

    project = _git_init(tmp_path / "real-project")
    (project / ".vnx-version").write_text(f"{_VERSION}\n", encoding="utf-8")
    subdir = project / "a" / "b"
    subdir.mkdir(parents=True)

    out = _run_shim(shim, subdir)
    assert out["VNX_PROJECT_ROOT"] == str(project)
    assert out["VNX_PROJECT_ROOT"] != _UNSET


# ── Traversal stops at the git boundary (no parent-project leak) ─────────────
def test_shim_stops_at_git_boundary(tmp_path):
    shim = _install_shim(tmp_path)

    # `outer` holds a .vnx-version pin but is NOT a git repo; `inner` is its own
    # git repo with no pin of its own. The shim must resolve VNX_HOME from the
    # outer pin (find_version_pin is unbounded) yet keep VNX_PROJECT_ROOT pinned
    # at the inner git root — never the outer dir above the git boundary.
    outer = tmp_path / "outer"
    outer.mkdir()
    (outer / ".vnx-version").write_text(f"{_VERSION}\n", encoding="utf-8")
    inner = _git_init(outer / "inner")

    out = _run_shim(shim, inner)
    assert out["VNX_PROJECT_ROOT"] == str(inner)
    assert out["VNX_PROJECT_ROOT"] != str(outer.resolve())


# ── No pin anywhere: fall back to the git root ───────────────────────────────
def test_shim_falls_back_to_git_root_without_pin(tmp_path):
    shim = _install_shim(tmp_path)

    # Project pinned via the central `current` symlink path is not needed here:
    # an outer pin lets the shim resolve VNX_HOME, while the project itself has
    # no pin, so VNX_PROJECT_ROOT must come from its git root.
    outer = tmp_path / "outer"
    outer.mkdir()
    (outer / ".vnx-version").write_text(f"{_VERSION}\n", encoding="utf-8")
    project = _git_init(outer / "proj")
    subdir = project / "src"
    subdir.mkdir()

    out = _run_shim(shim, subdir)
    assert out["VNX_PROJECT_ROOT"] == str(project)


# ── Inherited VNX_PROJECT_ROOT is cleared and re-detected ────────────────────
def test_shim_clears_inherited_vnx_project_root(tmp_path):
    shim = _install_shim(tmp_path)

    project = _git_init(tmp_path / "real-project")
    (project / ".vnx-version").write_text(f"{_VERSION}\n", encoding="utf-8")
    stale = _git_init(tmp_path / "stale-project")

    out = _run_shim(shim, project, extra_env={"VNX_PROJECT_ROOT": str(stale)})
    assert out["VNX_PROJECT_ROOT"] == str(project)
    assert out["VNX_PROJECT_ROOT"] != str(stale)


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(pytest.main([__file__, "-v"]))
