"""skill_prefix — provider-agnostic skill-content injection.

Reads SKILL.md files from a skill-library folder and builds a plain-text
prefix that any text-based LLM can consume — no `/skill` slash-command,
no `--skills-dir` CLI flag, no Skill() runtime tool dependency.

Architecture decision (Vincent 2026-06-05):
  - One SSOT skill-library folder (default: <repo>/.claude/skills/)
  - One injection function used by ALL provider lanes (claude/kimi/codex/deepseek)
  - Plain-text prepend; skill body + auto-generated resource-index
  - Worker reads references/scripts on-demand via Read/Bash tools

Trade-offs vs Claude-native Skill() runtime tool:
  - PRO: provider-agnostic, no syntax-divergence between CLIs
  - PRO: deterministic — operator sees exactly what was injected
  - PRO: works for headless lanes that lack runtime tool-loading
  - CON: ~750 tokens always loaded even if unused (negligible on subscription)
  - CON: no worker-driven runtime skill escalation — T0 pre-routes

For the bench-suite + dispatch-stack where T0 knows the specialist per
task ahead of time, the plain-prepend approach is strictly simpler and
matches actual usage patterns.
"""
from __future__ import annotations

from pathlib import Path
from typing import Iterable


_FRONTMATTER_DELIM = "---\n"
_RESOURCE_SUBDIRS = ("references", "scripts")
_MAX_FIRSTLINE_CHARS = 70


def _strip_frontmatter(text: str) -> str:
    """Remove YAML frontmatter block if present; return body only."""
    if not text.startswith(_FRONTMATTER_DELIM):
        return text
    parts = text.split(_FRONTMATTER_DELIM, 2)
    if len(parts) < 3:
        return text
    return parts[2].lstrip()


def _firstline_summary(path: Path) -> str:
    """Return a short single-line description of a resource file."""
    try:
        for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
            stripped = line.strip().lstrip("#").lstrip("/").lstrip("*").strip()
            if stripped:
                return stripped[:_MAX_FIRSTLINE_CHARS]
    except OSError:
        return ""
    return ""


def _build_resource_index(folder: Path) -> str:
    """Build a human-readable index of references/, scripts/, and extra files."""
    lines: list[str] = [f"Skill folder: {folder.absolute()}\n"]

    for subdir_name in _RESOURCE_SUBDIRS:
        sub = folder / subdir_name
        if not sub.is_dir():
            continue
        verb = "Read" if subdir_name == "references" else "Bash"
        lines.append(f"\n{subdir_name.title()} (use {verb} on demand):")
        for f in sorted(sub.iterdir()):
            if not f.is_file():
                continue
            kb = max(1, f.stat().st_size // 1024)
            summary = _firstline_summary(f)
            suffix = f" — {summary}" if summary else ""
            lines.append(f"- {subdir_name}/{f.name} ({kb}KB){suffix}")

    # Loose top-level files besides SKILL.md (e.g. template.md).
    extras = sorted(
        p for p in folder.glob("*")
        if p.is_file() and p.name != "SKILL.md"
    )
    if extras:
        lines.append("\nAdditional files:")
        for f in extras:
            summary = _firstline_summary(f)
            suffix = f" — {summary}" if summary else ""
            lines.append(f"- {f.name}{suffix}")

    return "\n".join(lines)


def build_skill_prefix(
    skill_names: Iterable[str],
    skills_root: Path,
) -> str:
    """Build a plain-text prefix containing skill bodies + resource indexes.

    Returns empty string if no skills resolve (graceful no-op for tasks
    without a skill-binding).

    Format:
        # SKILL: <name>
        <SKILL.md body — frontmatter stripped>

        ## Aanvullende resources
        <auto-generated index of references/ + scripts/ + extras>

        ---

        # SKILL: <name-2>
        ...

        # USER INSTRUCTION:

    The "# USER INSTRUCTION:" trailer is the boundary marker — the caller
    appends the actual instruction after this prefix.
    """
    skill_names = [n for n in skill_names if n]
    if not skill_names:
        return ""

    sections: list[str] = []
    for name in skill_names:
        folder = skills_root / name
        skill_md = folder / "SKILL.md"
        if not skill_md.exists():
            continue

        body = _strip_frontmatter(skill_md.read_text(encoding="utf-8"))
        index = _build_resource_index(folder)
        sections.append(
            f"# SKILL: {name}\n\n{body}\n\n## Aanvullende resources\n\n{index}"
        )

    if not sections:
        return ""

    return "\n\n---\n\n".join(sections) + "\n\n# USER INSTRUCTION:\n\n"


def inject_skill_prefix_into_instruction(
    instruction: str,
    skill_names: Iterable[str],
    skills_root: Path,
) -> str:
    """Convenience wrapper: prepend skill-prefix to an instruction string."""
    prefix = build_skill_prefix(skill_names, skills_root)
    if not prefix:
        return instruction
    return prefix + instruction
