"""Operator-gated skill-body refinement proposals from rework attribution.

Slice 2 of the rework->skill loop. Slice 1 (rework_attribution.py) traces git churn back to the
originating dispatch and role. This module reads those attributions and proposes targeted edits
to the relevant skill files (.claude/skills/<role>/SKILL.md) for operator review.

Proposals are written to pending_skill_refinements.json in the state directory. Application
is a SEPARATE operator-approved step — this module NEVER modifies skill files directly.

Safe-by-design:
- Read-only w.r.t. skill markdown files.
- Proposals target ONLY .claude/skills/ (project-editable per CLAUDE.md), NEVER .vnx/skills/.
- Output written atomically (tmp + os.replace).
- Never raises: fail-open on missing DBs, missing skill files, or corrupt state.
"""

from __future__ import annotations

import datetime
import difflib
import json
import os
import sqlite3
from pathlib import Path
from typing import Dict, List, Optional, Tuple

REWORK_THRESHOLD = 0.3

_ACTIVATION_HEADING = "## Skill Activation Announcement"
_ATTRIBUTION_HEADING = "## Rework Attribution Signal"


def _utcnow_iso() -> str:
    return datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")


def compute_rework_rates(
    qi_conn: sqlite3.Connection,
    project_id: str,
) -> Dict[str, dict]:
    """Per-role rework rates: {role: {total, reworked, rework_rate}}.

    Joins success_by_role (governed totals, benchmark excluded) with
    rework_by_origin_role (how often each role's work was subsequently reworked).
    Roles with no governed dispatches or no rework data get rework_rate=0.0.
    """
    from rework_attribution import rework_by_origin_role, success_by_role

    role_stats = {r["role"]: r for r in success_by_role(qi_conn)}
    rework_counts = {
        r["origin_role"]: r["reworked"]
        for r in rework_by_origin_role(qi_conn, project_id)
        if r["origin_role"]
    }

    result: Dict[str, dict] = {}
    for role, stats in role_stats.items():
        if not role:
            continue
        reworked = rework_counts.get(role, 0)
        total = stats["total"]
        rate = round(reworked / total, 3) if total > 0 else 0.0
        result[role] = {
            "total": total,
            "reworked": reworked,
            "rework_rate": rate,
        }
    return result


def find_rework_prone_roles(
    qi_conn: sqlite3.Connection,
    project_id: str,
    threshold: float = REWORK_THRESHOLD,
) -> List[Tuple[str, dict]]:
    """Return (role, stats) pairs where rework_rate > threshold, sorted by rate descending."""
    rates = compute_rework_rates(qi_conn, project_id)
    prone = [(role, data) for role, data in rates.items() if data["rework_rate"] > threshold]
    return sorted(prone, key=lambda kv: kv[1]["rework_rate"], reverse=True)


def resolve_skill_path(project_root: "str | Path", role: str) -> Optional[Path]:
    """Return the path to .claude/skills/<role>/SKILL.md if it exists, else None.

    NEVER touches .vnx/skills/. The .claude/skills/ tree is the project-editable copy
    (CLAUDE.md: "after init this is the source of truth — edit skills here directly").
    """
    path = Path(project_root) / ".claude" / "skills" / role / "SKILL.md"
    return path if path.exists() else None


def _make_rework_section(
    role: str,
    rework_rate: float,
    reworked: int,
    total: int,
    generated_at: str,
) -> str:
    """Build the Rework Attribution Signal section to propose adding to the skill."""
    pct = f"{rework_rate:.0%}"
    return (
        f"{_ATTRIBUTION_HEADING}\n"
        f"\n"
        f"**Rework rate: {pct}** ({reworked} of {total} governed dispatches were subsequently reworked).\n"
        f"\n"
        f"This exceeds the 30% threshold. Evidence from `rework_attribution` provenance chain.\n"
        f"\n"
        f"### Rework-Reduction Checklist\n"
        f"\n"
        f"Before delivering, verify:\n"
        f"\n"
        f'- [ ] All stated acceptance criteria are fully met — no implicit "good enough"\n'
        f"- [ ] Downstream callers and tests still pass with your changes\n"
        f"- [ ] No partial implementations: if a step is incomplete, escalate before delivering\n"
        f"- [ ] Changes align with active ADRs (esp. ADR-007 for new tables)\n"
        f"- [ ] Codex Defense Checklist applied: atomic writes, null guards, negative-path tests\n"
        f"\n"
        f"> Generated by `vnx learning skill-refine` on {generated_at}.\n"
        f"> Operator: review, edit, then apply with `vnx learning skill-refine --apply`.\n"
    )


def _insert_section(original: str, section_text: str) -> str:
    """Insert section_text before ## Skill Activation Announcement, or append at end.

    Ensures a blank line before the inserted section.
    """
    lines = original.splitlines(keepends=True)

    insert_at = len(lines)
    for i, line in enumerate(lines):
        if line.rstrip() == _ACTIVATION_HEADING:
            insert_at = i
            break

    prefix: List[str] = []
    if insert_at > 0 and lines[insert_at - 1].strip():
        prefix = ["\n"]

    if not section_text.endswith("\n"):
        section_text += "\n"

    new_lines = lines[:insert_at] + prefix + [section_text] + lines[insert_at:]
    return "".join(new_lines)


def _generate_diff(original_content: str, new_content: str, skill_rel_path: str) -> str:
    """Return a unified diff string between original and new content.

    Every output line ends with exactly one newline (safe for JSON serialisation).
    """
    original_lines = original_content.splitlines(keepends=True)
    new_lines = new_content.splitlines(keepends=True)
    parts = []
    for line in difflib.unified_diff(
        original_lines,
        new_lines,
        fromfile=f"a/{skill_rel_path}",
        tofile=f"b/{skill_rel_path}",
        lineterm="",
    ):
        parts.append(line if line.endswith("\n") else line + "\n")
    return "".join(parts)


def generate_proposal(
    role: str,
    rework_rate: float,
    reworked_count: int,
    total_dispatches: int,
    skill_path: Path,
    project_root: "str | Path",
    generated_at: str,
) -> Optional[dict]:
    """Generate a single proposal dict. Returns None on any read error or idempotency guard.

    Idempotency: if the attribution heading already exists in the skill, returns None
    (re-proposing the same section would create a confusing duplicate diff).
    """
    try:
        original_content = skill_path.read_text(encoding="utf-8")
    except OSError:
        return None

    if _ATTRIBUTION_HEADING in original_content:
        return None

    skill_rel_path = str(skill_path.relative_to(Path(project_root)))
    section_text = _make_rework_section(
        role, rework_rate, reworked_count, total_dispatches, generated_at
    )
    new_content = _insert_section(original_content, section_text)
    diff = _generate_diff(original_content, new_content, skill_rel_path)

    if not diff:
        return None

    return {
        "id": f"skillref-{role}-{generated_at[:10].replace('-', '')}",
        "role": role,
        "skill_path": skill_rel_path,
        "rework_rate": rework_rate,
        "reworked_count": reworked_count,
        "total_dispatches": total_dispatches,
        "diff": diff,
        "rationale": (
            f"Role '{role}' has a rework rate of {rework_rate:.0%} "
            f"({reworked_count}/{total_dispatches} governed dispatches reworked). "
            f"Threshold is 30%. Adding a rework-reduction checklist to the skill "
            f"prompts the agent to apply first-time correctness practices."
        ),
        "operator_test": (
            f"1. Review the diff above — verify the checklist items make sense for {role}.\n"
            f"2. Edit the proposed section if needed (add role-specific anti-patterns).\n"
            f"3. Apply with: vnx learning skill-refine --apply\n"
            f"4. Verify: load the skill and confirm the rework section appears.\n"
            f"5. Monitor: after applying, watch whether the {role} rework rate improves "
            f"over the next 10 governed dispatches."
        ),
        "status": "pending",
        "generated_at": generated_at,
    }


def generate_all_proposals(
    qi_conn: sqlite3.Connection,
    project_id: str,
    project_root: "str | Path",
    threshold: float = REWORK_THRESHOLD,
    generated_at: Optional[str] = None,
) -> List[dict]:
    """Generate all skill-refinement proposals for rework-prone roles.

    Targets .claude/skills/ only. NEVER touches .vnx/skills/.
    Returns a list of proposal dicts; empty if no rework-prone roles or no skill files found.
    Best-effort: any per-role failure is silently skipped.
    """
    if generated_at is None:
        generated_at = _utcnow_iso()

    try:
        prone_roles = find_rework_prone_roles(qi_conn, project_id, threshold)
    except Exception:
        return []

    proposals = []
    for role, stats in prone_roles:
        skill_path = resolve_skill_path(project_root, role)
        if skill_path is None:
            continue
        try:
            proposal = generate_proposal(
                role=role,
                rework_rate=stats["rework_rate"],
                reworked_count=stats["reworked"],
                total_dispatches=stats["total"],
                skill_path=skill_path,
                project_root=project_root,
                generated_at=generated_at,
            )
        except Exception:
            continue
        if proposal is not None:
            proposals.append(proposal)
    return proposals


def write_proposals(
    proposals: List[dict],
    output_path: "str | Path",
    threshold: float = REWORK_THRESHOLD,
    generated_at: Optional[str] = None,
) -> None:
    """Atomically write pending_skill_refinements.json (tmp + os.replace)."""
    output_path = Path(output_path)
    if generated_at is None:
        generated_at = _utcnow_iso()

    payload = {
        "generated_at": generated_at,
        "threshold": threshold,
        "proposals": proposals,
    }
    tmp = Path(str(output_path) + ".tmp")
    tmp.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    os.replace(str(tmp), str(output_path))
