-- VNX Migration 0016 — Phase 6 P4 FTS5 rebuild
-- (Numbered 0016 because 0011-0014 were claimed by intervening migrations.)
--
-- ARCHITECTURE NOTE (ADR-009 / OI-1375 / OI-1376):
-- The code_snippets FTS5 rebuild is now fully Python-driven by
-- `apply_migration_0016` → `_rebuild_fts5_code_snippets` in
-- `scripts/migrate_to_central_vnx.py`.  That function derives the column
-- list from PRAGMA table_info at apply time (schema-first per ADR-009),
-- preserving any extra columns on deployed DBs, and attributes orphan
-- project_id values via p4_import_rowid_map before failing loud.
--
-- This SQL file is no longer executed by apply_migration_0016; it is kept
-- as documentation of the original intent and the perf-index rationale.
--
-- Companion plan: `claudedocs/2026-04-30-single-vnx-migration-plan.md` §4.4.

-- ============================================================================
-- DOCUMENTATION ONLY — statements below are superseded by the Python runner
-- ============================================================================

-- Round-4 perf fix: the project_id assignment uses a correlated subquery
-- against snippet_metadata.snippet_rowid. Without an index on that column
-- the rebuild does a full scan of snippet_metadata for each row in
-- code_snippets_rebuild_tmp (O(N×M)). On a real central with ~855k snippets
-- and ~119k metadata rows that is ~100B row scans / multi-hour runtime.
-- The Python runner creates this index directly before calling
-- _rebuild_fts5_code_snippets.
--
-- CREATE INDEX IF NOT EXISTS idx_snippet_metadata_rowid
-- ON snippet_metadata(snippet_rowid);

-- The code_snippets FTS5 rebuild (CREATE TABLE tmp, DROP, CREATE VIRTUAL
-- TABLE, INSERT, DROP tmp) that previously appeared here has been replaced
-- by _rebuild_fts5_code_snippets() in scripts/migrate_to_central_vnx.py.
-- That function:
--   1. Reads deployed column list via PRAGMA table_info (no hardcoded projection)
--   2. Checks for orphan rows and raises MigrationOrphanError before any DROP
--   3. Uses COALESCE(snippet_metadata, p4_import_rowid_map) for project_id

-- INSERT OR IGNORE INTO schema_version (version, description)
-- VALUES ('8.4.0-fts5-project-id',
--         'Phase 6 P4: rebuild FTS5 virtual tables with project_id column');
