#!/usr/bin/env python3
"""
Apply Suggested Edits — Human-in-the-loop CLI for system tuning.

Commands:
  review              Show all pending edits
  accept 1,3,5        Mark specific edits as accepted
  reject 2,4          Mark specific edits as rejected (with optional --reason)
  apply               Apply all accepted edits to target files
  history             Show previously applied edits

All edits come from pending_edits.json (generated by generate_suggested_edits.py).
Applied edits are archived to edit_history.json.
"""

import argparse
import json
import re
import sys
from collections import defaultdict
from datetime import datetime, timedelta, timezone

_UTC = timezone.utc
from pathlib import Path
from typing import List

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR / "lib"))
try:
    from vnx_paths import ensure_env
except Exception as exc:
    raise SystemExit(f"Failed to load vnx_paths: {exc}")

PATHS = ensure_env()
STATE_DIR = Path(PATHS["VNX_STATE_DIR"])
PROJECT_ROOT = Path(PATHS["PROJECT_ROOT"])
PENDING_PATH = STATE_DIR / "pending_edits.json"
HISTORY_PATH = STATE_DIR / "edit_history.json"


class Colors:
    GREEN = '\033[92m'
    RED = '\033[91m'
    YELLOW = '\033[93m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    BOLD = '\033[1m'
    RESET = '\033[0m'


def _load_pending() -> dict:
    if not PENDING_PATH.exists():
        return {"generated_at": "", "edits": []}
    try:
        return json.loads(PENDING_PATH.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, KeyError):
        return {"generated_at": "", "edits": []}


def _save_pending(data: dict):
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    PENDING_PATH.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")


def _load_history() -> list:
    if HISTORY_PATH.exists():
        try:
            return json.loads(HISTORY_PATH.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, KeyError):
            pass
    return []


def _save_history(history: list):
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    HISTORY_PATH.write_text(json.dumps(history, indent=2, ensure_ascii=False), encoding="utf-8")


def _resolve_target_path(target: str) -> Path:
    """Resolve a target path relative to PROJECT_ROOT or as absolute."""
    target_path = Path(target)
    if target_path.is_absolute():
        return target_path
    # Relative to PROJECT_ROOT
    candidate = PROJECT_ROOT / target
    if candidate.exists():
        return candidate
    # Try home-relative (~/)
    if target.startswith("~/"):
        return Path(target).expanduser()
    return candidate


def _parse_ids(id_str: str) -> List[int]:
    """Parse comma-separated IDs like '1,3,5'."""
    ids = []
    for part in id_str.split(","):
        part = part.strip()
        if part.isdigit():
            ids.append(int(part))
    return ids


def cmd_review_weekly():
    """Show weekly aggregated view of suggestions grouped by target file."""
    now = datetime.now(tz=_UTC)
    cutoff = now - timedelta(days=7)

    history = _load_history()
    recent_history = []
    for entry in history:
        applied_at_str = entry.get("applied_at", "")
        if applied_at_str:
            try:
                ts = datetime.fromisoformat(applied_at_str.replace("Z", "+00:00"))
                if ts.tzinfo is None:
                    ts = ts.replace(tzinfo=_UTC)
                if ts >= cutoff:
                    recent_history.append(entry)
            except ValueError:
                pass

    data = _load_pending()
    pending = data.get("edits", [])

    all_entries = [{**e, "_source": "pending"} for e in pending]
    all_entries += [{**e, "_source": "history"} for e in recent_history]

    if not all_entries:
        print("No suggestions in the last 7 days.")
        return 0

    by_target: dict = defaultdict(list)
    for entry in all_entries:
        by_target[entry.get("target", "unknown")].append(entry)

    print(f"\n{Colors.BOLD}Weekly Suggestions Summary (last 7 days){Colors.RESET}")
    print(f"Targets with suggestions: {len(by_target)}\n")

    for target, entries in sorted(by_target.items(), key=lambda kv: -len(kv[1])):
        count = len(entries)
        confidences = [float(e.get("confidence", 0)) for e in entries if e.get("confidence") is not None]
        avg_conf = sum(confidences) / len(confidences) if confidences else 0.0

        print(f"  {Colors.BOLD}{target}{Colors.RESET} "
              f"— {count} suggestion(s), avg confidence: {avg_conf:.2f}")

        for entry in entries:
            eid = entry.get("id", "?")
            status = entry.get("status", "pending")
            content = entry.get("content", "")
            content_preview = content.strip().split("\n")[0][:80] if content else ""
            source = entry.get("_source", "pending")

            if source == "history":
                status_label = f"[{Colors.GREEN}applied{Colors.RESET}]"
            elif status == "pending":
                status_label = f"[{Colors.YELLOW}pending{Colors.RESET}]"
            elif status == "accepted":
                status_label = f"[{Colors.GREEN}accepted{Colors.RESET}]"
            else:
                status_label = f"[{Colors.RED}{status}{Colors.RESET}]"

            if count > 1:
                print(f"    Pattern detected ({count} occurrences, last 7d): {content_preview}")
            else:
                print(f"    #{eid} {status_label} {content_preview}")

        pending_ids = [
            str(e["id"])
            for e in entries
            if e.get("_source") == "pending" and e.get("status") == "pending" and e.get("id") is not None
        ]
        if pending_ids:
            print(f"    Accept batch: vnx suggest accept {','.join(pending_ids)}")
        print()

    return 0


def cmd_review(weekly: bool = False):
    """Show all pending edits."""
    if weekly:
        return cmd_review_weekly()

    data = _load_pending()
    edits = data.get("edits", [])

    if not edits:
        print("No pending edits.")
        return 0

    cat_colors = {
        "memory": Colors.BLUE,
        "rule": Colors.YELLOW,
        "claude_md": Colors.CYAN,
        "skill": Colors.GREEN,
        "hook": Colors.RED,
    }
    cat_labels = {
        "memory": "MEMORY",
        "rule": "RULE",
        "claude_md": "CLAUDE.MD",
        "skill": "SKILL",
        "hook": "HOOK",
    }

    status_colors = {
        "pending": Colors.YELLOW,
        "accepted": Colors.GREEN,
        "rejected": Colors.RED,
    }

    print(f"\n{Colors.BOLD}Pending Suggested Edits{Colors.RESET}")
    print(f"Generated: {data.get('generated_at', 'unknown')}\n")

    for edit in edits:
        eid = edit.get("id", "?")
        cat = edit.get("category", "unknown")
        status = edit.get("status", "pending")
        target = edit.get("target", "")
        action = edit.get("action", "append")
        content = edit.get("content", "")
        confidence = edit.get("confidence", 0)
        evidence = edit.get("evidence", "")

        cat_color = cat_colors.get(cat, Colors.RESET)
        cat_label = cat_labels.get(cat, cat.upper())
        status_color = status_colors.get(status, Colors.RESET)

        print(f"  {Colors.BOLD}#{eid}{Colors.RESET} "
              f"[{cat_color}{cat_label}{Colors.RESET}] "
              f"({status_color}{status}{Colors.RESET})")
        print(f"    Target: {target}")
        print(f"    Action: {action}")

        # Show content preview (first 2 lines)
        content_lines = content.strip().split("\n")
        for line in content_lines[:2]:
            print(f"    {Colors.CYAN}{line}{Colors.RESET}")
        if len(content_lines) > 2:
            print(f"    ... ({len(content_lines) - 2} more lines)")

        print(f"    Confidence: {confidence:.2f} | Evidence: {evidence}")

        if edit.get("reject_reason"):
            print(f"    Reject reason: {edit['reject_reason']}")
        print()

    pending_count = sum(1 for e in edits if e.get("status") == "pending")
    accepted_count = sum(1 for e in edits if e.get("status") == "accepted")
    print(f"  Pending: {pending_count} | Accepted: {accepted_count}")
    print(f"\n  Accept: vnx suggest accept <ids>")
    print(f"  Reject: vnx suggest reject <ids> [--reason '...']")
    print(f"  Apply:  vnx suggest apply")

    return 0


def cmd_accept(id_str: str):
    """Mark edits as accepted."""
    ids = _parse_ids(id_str)
    if not ids:
        print("No valid IDs provided.", file=sys.stderr)
        return 1

    data = _load_pending()
    edits = data.get("edits", [])
    accepted = []

    for edit in edits:
        if edit.get("id") in ids and edit.get("status") == "pending":
            edit["status"] = "accepted"
            edit["accepted_at"] = datetime.now(tz=_UTC).isoformat().replace("+00:00", "Z")
            accepted.append(edit["id"])

    _save_pending(data)

    if accepted:
        print(f"{Colors.GREEN}Accepted: {', '.join(f'#{i}' for i in accepted)}{Colors.RESET}")
    else:
        print("No matching pending edits found for the given IDs.")
    return 0


def cmd_reject(id_str: str, reason: str = ""):
    """Mark edits as rejected."""
    ids = _parse_ids(id_str)
    if not ids:
        print("No valid IDs provided.", file=sys.stderr)
        return 1

    data = _load_pending()
    edits = data.get("edits", [])
    rejected = []

    for edit in edits:
        if edit.get("id") in ids and edit.get("status") in ("pending", "accepted"):
            edit["status"] = "rejected"
            edit["rejected_at"] = datetime.now(tz=_UTC).isoformat().replace("+00:00", "Z")
            if reason:
                edit["reject_reason"] = reason
            rejected.append(edit["id"])

    _save_pending(data)

    if rejected:
        print(f"{Colors.RED}Rejected: {', '.join(f'#{i}' for i in rejected)}{Colors.RESET}")
    else:
        print("No matching pending/accepted edits found for the given IDs.")
    return 0


def _apply_memory_edit(edit: dict) -> bool:
    """Append a line to a section in a MEMORY.md file."""
    target = _resolve_target_path(edit["target"])
    section = edit.get("section", "## Geleerde Patronen")
    content = edit.get("content", "")

    if not target.exists():
        # Create with section header
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(f"{section}\n\n{content}\n", encoding="utf-8")
        return True

    text = target.read_text(encoding="utf-8")

    # Find section and append after it
    section_pattern = re.escape(section)
    match = re.search(rf"^{section_pattern}\s*$", text, re.MULTILINE)

    if match:
        # Find the end of the section (next ## or end of file)
        section_end = match.end()
        next_section = re.search(r"^## ", text[section_end:], re.MULTILINE)
        if next_section:
            insert_pos = section_end + next_section.start()
            text = text[:insert_pos] + content + "\n" + text[insert_pos:]
        else:
            text = text.rstrip() + "\n" + content + "\n"
    else:
        # Section doesn't exist — append at end
        text = text.rstrip() + "\n\n" + section + "\n\n" + content + "\n"

    target.write_text(text, encoding="utf-8")
    return True


def _apply_rule_edit(edit: dict) -> bool:
    """Replace content in a rules file."""
    target = _resolve_target_path(edit["target"])
    if not target.exists():
        print(f"  Rule file not found: {target}", file=sys.stderr)
        return False

    old_content = edit.get("old_content", "")
    new_content = edit.get("content", "")

    if not old_content:
        print(f"  No old_content for rule replacement", file=sys.stderr)
        return False

    text = target.read_text(encoding="utf-8")
    if old_content not in text:
        print(f"  old_content not found in {target.name}", file=sys.stderr)
        return False

    text = text.replace(old_content, new_content, 1)
    target.write_text(text, encoding="utf-8")
    return True


def _apply_claude_md_edit(edit: dict) -> bool:
    """Append a section to a CLAUDE.md file."""
    target = _resolve_target_path(edit["target"])
    if not target.exists():
        print(f"  CLAUDE.md not found: {target}", file=sys.stderr)
        return False

    content = edit.get("content", "")
    text = target.read_text(encoding="utf-8")

    # Check if section already exists
    section_header = content.split("\n")[0] if content else ""
    if section_header and section_header in text:
        print(f"  Section already exists in {target.name}", file=sys.stderr)
        return False

    text = text.rstrip() + "\n\n" + content + "\n"
    target.write_text(text, encoding="utf-8")
    return True


def _apply_skill_edit(edit: dict) -> bool:
    """Append a section to a skill template file."""
    target = _resolve_target_path(edit["target"])
    if not target.exists():
        print(f"  Skill template not found: {target}", file=sys.stderr)
        return False

    content = edit.get("content", "")
    text = target.read_text(encoding="utf-8")

    section_header = content.split("\n")[0] if content else ""
    if section_header and section_header in text:
        print(f"  Section already exists in {target.name}", file=sys.stderr)
        return False

    text = text.rstrip() + "\n\n" + content + "\n"
    target.write_text(text, encoding="utf-8")
    return True


APPLY_HANDLERS = {
    "memory": _apply_memory_edit,
    "rule": _apply_rule_edit,
    "claude_md": _apply_claude_md_edit,
    "skill": _apply_skill_edit,
}


def cmd_apply():
    """Apply all accepted edits."""
    data = _load_pending()
    edits = data.get("edits", [])
    history = _load_history()

    accepted = [e for e in edits if e.get("status") == "accepted"]
    if not accepted:
        print("No accepted edits to apply. Use 'vnx suggest accept <ids>' first.")
        return 0

    applied = []
    failed = []

    for edit in accepted:
        eid = edit.get("id", "?")
        cat = edit.get("category", "unknown")
        handler = APPLY_HANDLERS.get(cat)

        if not handler:
            print(f"  #{eid}: Unknown category '{cat}' — skipped")
            failed.append(eid)
            continue

        print(f"  Applying #{eid} [{cat}] → {edit.get('target', '?')}...", end=" ")
        try:
            if handler(edit):
                edit["status"] = "applied"
                edit["applied_at"] = datetime.now(tz=_UTC).isoformat().replace("+00:00", "Z")
                applied.append(eid)
                print(f"{Colors.GREEN}OK{Colors.RESET}")

                # Archive to history
                history.append({
                    **edit,
                    "applied_at": edit["applied_at"],
                })
            else:
                failed.append(eid)
                print(f"{Colors.RED}FAILED{Colors.RESET}")
        except Exception as e:
            failed.append(eid)
            print(f"{Colors.RED}ERROR: {e}{Colors.RESET}")

    # Remove applied edits from pending
    data["edits"] = [e for e in edits if e.get("status") != "applied"]
    _save_pending(data)
    _save_history(history)

    print(f"\n{Colors.GREEN}Applied: {len(applied)}{Colors.RESET} | "
          f"{Colors.RED}Failed: {len(failed)}{Colors.RESET}")
    return 0 if not failed else 1


def cmd_history():
    """Show previously applied edits."""
    history = _load_history()
    if not history:
        print("No edit history.")
        return 0

    print(f"\n{Colors.BOLD}Edit History ({len(history)} entries){Colors.RESET}\n")

    for entry in history[-20:]:  # Show last 20
        eid = entry.get("id", "?")
        cat = entry.get("category", "?")
        target = entry.get("target", "?")
        applied_at = entry.get("applied_at", "?")
        content_preview = entry.get("content", "")[:60]

        print(f"  #{eid} [{cat.upper()}] {target}")
        print(f"    Applied: {applied_at}")
        print(f"    Content: {content_preview}")
        print()

    return 0


def main():
    parser = argparse.ArgumentParser(
        description="Apply Suggested Edits — Human-in-the-loop system tuning CLI")

    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    review_parser = subparsers.add_parser("review", help="Show all pending edits")
    review_parser.add_argument(
        "--weekly", action="store_true",
        help="Aggregate last 7 days of suggestions grouped by target file",
    )

    accept_parser = subparsers.add_parser("accept", help="Accept edits by ID")
    accept_parser.add_argument("ids", help="Comma-separated edit IDs (e.g., 1,3,5)")

    reject_parser = subparsers.add_parser("reject", help="Reject edits by ID")
    reject_parser.add_argument("ids", help="Comma-separated edit IDs (e.g., 2,4)")
    reject_parser.add_argument("--reason", default="", help="Reason for rejection")

    subparsers.add_parser("apply", help="Apply all accepted edits")
    subparsers.add_parser("history", help="Show applied edit history")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        return 1

    if args.command == "review":
        return cmd_review(weekly=getattr(args, "weekly", False))
    elif args.command == "accept":
        return cmd_accept(args.ids)
    elif args.command == "reject":
        return cmd_reject(args.ids, args.reason)
    elif args.command == "apply":
        return cmd_apply()
    elif args.command == "history":
        return cmd_history()

    return 1


if __name__ == "__main__":
    sys.exit(main())
