#!/usr/bin/env python3
"""Project root ROADMAP.yaml into the strategy module's Roadmap/Wave schema.

Reads the authored SSOT (root ROADMAP.yaml, 30+ features) and projects it into
the typed Roadmap dataclass from ``scripts/lib/strategy/roadmap.py``, then
writes ``.vnx-data/strategy/roadmap.yaml`` via ``write_roadmap()`` so
``loaders.py:_load_roadmap_safe`` succeeds.

If ``.vnx-data/strategy/decisions.ndjson`` is absent (first run), seeds it
with 4 2026-06-01 operator decisions via ``record_decision()``.

Mapping decisions
-----------------
Root ROADMAP features are a flat list. The strategy Roadmap schema has
phases (grouping construct) and waves (individual units). Each root
feature maps to one Wave:

  feature_id       -> wave_id (preserved verbatim)
  title            -> title
  status           -> status   ("done"|"shipped-dark" -> "completed",
                                "planned" -> "planned")
  depends_on       -> depends_on (list of feature_ids, preserved)
  risk_class       -> risk_class
  branch_name      -> branch_name
  review_stack     -> review_stack
  plan_path        -> plan_path
  notes            -> notes

Phases are derived by grouping features on their ``milestone`` field
(1.0 -> phase 1, 1.0.1 -> phase 2, 1.1 -> phase 3, 1.2 -> phase 4,
1.x -> phase 5). This is a mechanical mapping: the root ROADMAP has no
native phase concept, and the strategy schema requires at least one
phase per wave. Grouping by milestone preserves the intended delivery
cadence.

next_actionable_wave resolves to the first planned wave with all
depends_on waves completed. With the current ROADMAP state this is
``provider-lanes-doc-pass`` (no deps, milestone 1.0, status planned).

Idempotent: rerunning overwrites .vnx-data/strategy/roadmap.yaml cleanly.
Decisions are append-only; seeding is skipped when decisions.ndjson exists.

Usage:
    python3 scripts/build_strategy_projection.py [--dry-run]

Generated artifacts (NOT committed):
    .vnx-data/strategy/roadmap.yaml
    .vnx-data/strategy/decisions.ndjson  (seeded on first run only)
"""

from __future__ import annotations

import argparse
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

# ---------------------------------------------------------------------------
# Path bootstrap
# ---------------------------------------------------------------------------
_SCRIPT_DIR = Path(__file__).resolve().parent
_LIB_DIR = _SCRIPT_DIR / "lib"
if str(_LIB_DIR) not in sys.path:
    sys.path.insert(0, str(_LIB_DIR))

_REPO_ROOT = _SCRIPT_DIR.parent
_ROOT_ROADMAP = _REPO_ROOT / "ROADMAP.yaml"
_DATA_DIR = _REPO_ROOT / ".vnx-data"

# Generated-file header (YAML comment)
_GENERATED_HEADER = (
    "# =============================================================================\n"
    "# AUTO-GENERATED by scripts/build_strategy_projection.py\n"
    "# Source: ROADMAP.yaml (root, authored SSOT)\n"
    "# DO NOT EDIT — regenerate with: python3 scripts/build_strategy_projection.py\n"
    "# ============================================================================="
)

# Status mapping: root ROADMAP status -> strategy Wave status
_STATUS_MAP: dict[str, str] = {
    "done": "completed",
    "shipped-dark": "completed",
    "merged": "completed",
    "planned": "planned",
    "in_progress": "in_progress",
    "deferred": "deferred",
    "cancelled": "cancelled",
}

# Milestone -> phase_id grouping
_MILESTONE_PHASE_MAP: dict[str, int] = {
    "1.0": 1,
    "1.0.1": 2,
    "1.1": 3,
    "1.2": 4,
    "1.x": 5,
}

# Phase titles
_PHASE_TITLES: dict[int, str] = {
    1: "1.0 Launch",
    2: "1.0.1 Hardening",
    3: "1.1 Capability Binding & Provider Parity",
    4: "1.2 Smart Routing & Usage",
    5: "1.x Future State",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _resolve_data_dir() -> Path:
    env_data = os.environ.get("VNX_DATA_DIR")
    if env_data:
        return Path(env_data)
    return _DATA_DIR


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _load_root_roadmap(path: Path) -> dict[str, Any]:
    """Load the authored ROADMAP.yaml. Raises on missing/malformed."""
    import yaml

    if not path.exists():
        raise FileNotFoundError(f"root ROADMAP.yaml not found: {path}")

    with path.open("r", encoding="utf-8") as fh:
        data = yaml.safe_load(fh)

    if not isinstance(data, dict):
        raise ValueError(f"ROADMAP.yaml root must be a mapping, got {type(data).__name__}")
    if "features" not in data:
        raise ValueError("ROADMAP.yaml missing 'features' key")
    return data


def _map_status(root_status: str) -> str:
    mapped = _STATUS_MAP.get(root_status)
    if mapped is None:
        print(
            f"[build_strategy_projection] unknown status '{root_status}' "
            f"— defaulting to 'planned'",
            file=sys.stderr,
        )
        return "planned"
    return mapped


def _resolve_phase_id(milestone: Optional[str]) -> int:
    if milestone is None:
        return 5  # default to 1.x
    return _MILESTONE_PHASE_MAP.get(str(milestone), 5)


# ---------------------------------------------------------------------------
# Core projection
# ---------------------------------------------------------------------------

def build_projection(
    root_roadmap_path: Path | None = None,
    now_iso: str | None = None,
):
    """Project root ROADMAP into a typed strategy Roadmap object.

    Returns a ``Roadmap`` instance (not a dict). Does NOT write to disk.
    """
    from strategy.roadmap import (
        WAVE_STATUSES,
        RISK_CLASSES,
        Phase,
        Roadmap,
        Wave,
    )

    path = root_roadmap_path or _ROOT_ROADMAP
    root = _load_root_roadmap(path)
    features: list[dict] = root.get("features") or []
    roadmap_id = str(root.get("roadmap_id", "vnx-roadmap-autopilot"))
    title = str(root.get("title", "VNX Multi-Feature Roadmap"))
    generated_at = now_iso or _now_iso()

    # --- Build waves ---
    waves: list[Wave] = []
    feature_ids: set[str] = set()
    phase_ids_seen: set[int] = set()

    for feature in features:
        fid = str(feature.get("feature_id", ""))
        if not fid:
            print(
                "[build_strategy_projection] skipping feature with empty feature_id",
                file=sys.stderr,
            )
            continue
        feature_ids.add(fid)

        raw_status = str(feature.get("status", "planned"))
        status = _map_status(raw_status)
        if status not in WAVE_STATUSES:
            status = "planned"

        milestone = feature.get("milestone")
        phase_id = _resolve_phase_id(milestone)
        phase_ids_seen.add(phase_id)

        risk_class = str(feature.get("risk_class", "low"))
        if risk_class not in RISK_CLASSES:
            risk_class = "low"

        depends_on: list[str] = [
            str(d) for d in (feature.get("depends_on") or []) if d
        ]

        review_stack: list[str] = [
            str(r) for r in (feature.get("review_stack") or []) if r
        ]

        # Optional fields
        branch_name = feature.get("branch_name")
        branch_name = str(branch_name) if branch_name else None

        plan_path = feature.get("plan_path")
        plan_path = str(plan_path) if plan_path else None

        notes = feature.get("notes")
        notes = str(notes).strip() if notes else None

        pr_number = None
        pr_queue = feature.get("pr_queue") or []
        if pr_queue:
            for pq in pr_queue:
                pr_id = pq.get("pr_id") or ""
                if pr_id.startswith("#"):
                    try:
                        pr_number = int(pr_id.lstrip("#"))
                    except (ValueError, TypeError):
                        pass
                    break

        wave = Wave(
            wave_id=fid,
            title=str(feature.get("title", fid)),
            phase_id=phase_id,
            status=status,
            risk_class=risk_class,
            depends_on=depends_on,
            review_stack=review_stack,
            branch_name=branch_name,
            plan_path=plan_path,
            notes=notes,
            pr_number=pr_number,
        )
        waves.append(wave)

    # --- Validate depends_on references ---
    for w in waves:
        for dep in w.depends_on:
            if dep not in feature_ids:
                print(
                    f"[build_strategy_projection] wave {w.wave_id}: "
                    f"depends_on '{dep}' not found in feature list — "
                    f"this will cause a dangling-reference validation error",
                    file=sys.stderr,
                )

    # --- Reorder waves for dependency-aware next_actionable_wave ---
    # ``next_actionable_wave()`` returns the first planned wave in list
    # order whose deps are all completed. Sort so zero-dep planned waves
    # surface before waves with deps (even if those deps are completed).
    # This ensures ``provider-lanes-doc-pass`` (0 deps) resolves before
    # ``launch-option-b-parity`` (3 completed deps) when both are planned.
    completed_statuses = {"completed"}
    wave_status_map = {w.wave_id: w.status for w in waves}

    def _dep_sort_key(w: Wave) -> tuple[int, int, int, int]:
        """Sort waves by (status_priority, unmet_deps, phase_id, total_deps).

        Completed waves (prio 0) come first, preserving historical order.
        Planned waves (prio 1) are topo-sorted: zero-unmet-dep features in
        earlier phases surface first, so ``next_actionable_wave`` resolves
        to ``provider-lanes-doc-pass`` (phase 1, 0 deps) rather than
        ``launch-option-b-parity`` (phase 3, 3 deps, all completed).
        """
        if w.status == "completed":
            status_prio = 0
        elif w.status == "planned":
            status_prio = 1
        else:
            status_prio = 2
        unmet = sum(
            1 for d in w.depends_on
            if wave_status_map.get(d) not in completed_statuses
        )
        return (status_prio, unmet, w.phase_id, len(w.depends_on))

    waves.sort(key=_dep_sort_key)

    # --- Build phases ---
    phases: list[Phase] = []
    for pid in sorted(phase_ids_seen):
        phase_wave_ids = [w.wave_id for w in waves if w.phase_id == pid]
        phases.append(Phase(
            phase_id=pid,
            title=_PHASE_TITLES.get(pid, f"Phase {pid}"),
            waves=phase_wave_ids,
        ))

    # --- Build completed_history from completed waves ---
    completed_history: list[dict] = []
    for w in waves:
        if w.status == "completed":
            entry: dict[str, Any] = {
                "wave_id": w.wave_id,
                "title": w.title,
                "completed_at": generated_at[:10],
            }
            if w.pr_number:
                entry["pr"] = f"#{w.pr_number}"
            completed_history.append(entry)

    return Roadmap(
        schema_version=1,
        roadmap_id=roadmap_id,
        title=title,
        generated_at=generated_at,
        phases=phases,
        waves=waves,
        operator_decisions=[],
        completed_history=completed_history,
        notes={
            "source": "ROADMAP.yaml",
            "generator": "scripts/build_strategy_projection.py",
            "warning": (
                "Generated projection. Edit ROADMAP.yaml (root SSOT), not this file."
            ),
        },
    )


# ---------------------------------------------------------------------------
# Write
# ---------------------------------------------------------------------------
def write_strategy_roadmap(
    roadmap: Any,
    output_dir: Path | None = None,
    *,
    dry_run: bool = False,
) -> Path:
    """Write the projected Roadmap via ``write_roadmap()``.

    *roadmap* must be a typed ``Roadmap`` instance (the strategy module
    enforces schema and cross-reference validation during write).

    Returns the path that was (or would be) written.
    """
    from strategy.roadmap import write_roadmap

    target_dir = output_dir or (_resolve_data_dir() / "strategy")
    target_path = target_dir / "roadmap.yaml"

    if dry_run:
        n_waves = len(getattr(roadmap, "waves", []))
        print(f"[dry-run] would write {n_waves} waves to {target_path}")
        return target_path

    target_dir.mkdir(parents=True, exist_ok=True)
    write_roadmap(roadmap, target_path)

    # Prepend the generated-header comment (write_roadmap doesn't support
    # header injection; we insert it after writing by prepending).
    existing = target_path.read_text(encoding="utf-8")
    target_path.write_text(_GENERATED_HEADER + "\n" + existing, encoding="utf-8")

    print(
        f"[build_strategy_projection] wrote {len(roadmap.waves)} waves "
        f"to {target_path}"
    )
    return target_path


# ---------------------------------------------------------------------------
# Seed decisions
# ---------------------------------------------------------------------------


def _decisions_path(output_dir: Path | None = None) -> Path:
    target_dir = output_dir or (_resolve_data_dir() / "strategy")
    return target_dir / "decisions.ndjson"


_SEED_DECISIONS: list[dict[str, str]] = [
    {
        "decision_id": "OD-2026-06-01-001",
        "scope": "GAP 3b: receipt hash-chain",
        "rationale": (
            "GAP 3b hash-chain: DROP the README per-append-hash-chain claim "
            "now, WIRE in 1.0.1 (lock-scoped in idempotency.py + epoch "
            "rotation). 4-architect unanimous."
        ),
    },
    {
        "decision_id": "OD-2026-06-01-002",
        "scope": "GAP 5: report_pipeline retention",
        "rationale": (
            "GAP 5: KEEP report_pipeline (load-bearing: Stop hook + "
            "subprocess_adapter + gate_artifacts). Do not retire."
        ),
    },
    {
        "decision_id": "OD-2026-06-01-003",
        "scope": "Planning object-model architecture",
        "rationale": (
            "Planning object-model: NO-NODE. TRACK->DISPATCH(output_ref "
            "pluggable)->output/receipt; deliverable = derived view; "
            "OI separate. Domain-agnostic for Business OS. 4-architect "
            "+ 2nd-round debate."
        ),
    },
    {
        "decision_id": "OD-2026-06-01-004",
        "scope": "FUT-1/2 tracks-layer activation",
        "rationale": (
            "Activated dark FUT-1/2 tracks layer on live coordination DB "
            "via structural-doctor (#782); backup + ADR-005 audit; "
            "291 dispatches preserved."
        ),
    },
]


def seed_decisions(
    output_dir: Path | None = None,
    *,
    dry_run: bool = False,
) -> list[dict[str, str]]:
    """Append 2026-06-01 decisions via ``record_decision()``.

    Idempotent per decision_id: if a decision with the same ID already
    exists in decisions.ndjson, it is skipped. Returns the list of
    actually-appended decision IDs (empty on rerun).
    """
    from strategy.decisions import record_decision

    target_path = _decisions_path(output_dir)
    target_dir = target_path.parent

    # Read existing decision IDs
    existing_ids: set[str] = set()
    if target_path.exists():
        try:
            import json

            for line in target_path.read_text(encoding="utf-8").splitlines():
                if not line.strip():
                    continue
                try:
                    entry = json.loads(line)
                    eid = entry.get("decision_id", "")
                    if eid:
                        existing_ids.add(eid)
                except json.JSONDecodeError:
                    continue
        except OSError:
            pass

    appended: list[dict[str, str]] = []
    for decision in _SEED_DECISIONS:
        if decision["decision_id"] in existing_ids:
            print(
                f"[build_strategy_projection] decision "
                f"{decision['decision_id']} already exists — skipping"
            )
            continue

        if dry_run:
            print(
                f"[dry-run] would record {decision['decision_id']}: "
                f"{decision['scope']}"
            )
            appended.append(decision)
            continue

        target_dir.mkdir(parents=True, exist_ok=True)
        record_decision(
            decision_id=decision["decision_id"],
            scope=decision["scope"],
            rationale=decision["rationale"],
            path=target_path,
        )
        print(
            f"[build_strategy_projection] recorded {decision['decision_id']}"
        )
        appended.append(decision)

    return appended


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Project root ROADMAP.yaml into strategy/roadmap.yaml + seed "
            "decisions.ndjson"
        )
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be written; do not write files",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Output directory (default: .vnx-data/strategy/)",
    )
    parser.add_argument(
        "--skip-decisions",
        action="store_true",
        help="Skip decision seeding (only write roadmap)",
    )
    parser.add_argument(
        "--skip-roadmap",
        action="store_true",
        help="Skip roadmap projection (only seed decisions)",
    )
    args = parser.parse_args()

    output_dir = Path(args.output_dir) if args.output_dir else None
    errors = 0

    if not args.skip_roadmap:
        try:
            projection = build_projection()
            write_strategy_roadmap(projection, output_dir, dry_run=args.dry_run)
        except Exception as exc:
            print(f"[build_strategy_projection] roadmap projection failed: {exc}",
                  file=sys.stderr)
            errors += 1

    if not args.skip_decisions:
        try:
            appended = seed_decisions(output_dir, dry_run=args.dry_run)
            if appended:
                print(
                    f"[build_strategy_projection] seeded {len(appended)} "
                    f"decisions"
                )
            else:
                print(
                    "[build_strategy_projection] no new decisions to seed"
                )
        except Exception as exc:
            print(f"[build_strategy_projection] decision seeding failed: {exc}",
                  file=sys.stderr)
            errors += 1

    return min(errors, 1)


if __name__ == "__main__":
    sys.exit(main())
