#!/usr/bin/env python3
"""Build PROJECT_STATUS.md — auto-generated cold-start orientation document.

Replaces handwritten HANDOVER.md. Rebuilt on every receipt-append for completion
or dispatch-promotion events (via state_rebuild_trigger).

Schema: typed sections in MEMORY.md style. ≤100 lines.
"""
from __future__ import annotations
import json
import sys
from pathlib import Path
from datetime import datetime, timezone

_REPO_ROOT = Path(__file__).resolve().parents[1]


def build_project_status(state_dir: Path | None = None) -> str:
    """Build PROJECT_STATUS.md content from current state files."""
    state_dir = state_dir or _resolve_state_dir()

    # Load index (cheap)
    index_path = state_dir / "t0_index.json"
    index = json.loads(index_path.read_text(encoding="utf-8")) if index_path.exists() else {}

    # Load open items digest
    oi_path = state_dir / "open_items_digest.json"
    oi = json.loads(oi_path.read_text(encoding="utf-8")) if oi_path.exists() else {}

    # Load register events tail
    register_path = state_dir / "dispatch_register.ndjson"
    register_events = []
    if register_path.exists():
        for line in register_path.read_text(encoding="utf-8", errors="replace").splitlines()[-20:]:
            try:
                register_events.append(json.loads(line))
            except json.JSONDecodeError:
                continue

    # Compose
    now_iso = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
    lines = [
        f"# Project Status — {now_iso}",
        "",
        "<!-- AUTO-GENERATED by scripts/build_project_status.py — DO NOT EDIT -->",
        "",
        "## Summary",
        f"- Branch: `{index.get('git_branch','?')}` @ `{index.get('git_head','?')}`",
        f"- Open PRs: {index.get('queue',{}).get('open_prs',0)}",
        f"- Active dispatches: {index.get('queue',{}).get('active',0)}",
        f"- Pending dispatches: {index.get('queue',{}).get('pending',0)}",
        f"- Open items (blockers): {index.get('queue',{}).get('blocking_open_items',0)}",
        "",
        "## Terminals",
    ]
    for tid, t in (index.get("terminals") or {}).items():
        lines.append(f"- {tid}: {t.get('status','?')}")

    lines.extend(["", "## Recent activity (last 5 register events)"])
    for ev in register_events[-5:]:
        ts = ev.get("timestamp", "")[:19]
        lines.append(f"- {ts} {ev.get('event','')} dispatch={ev.get('dispatch_id','')[:30]}")

    lines.extend(["", "## Health"])
    health = index.get("health", {})
    for k, v in health.items():
        lines.append(f"- {k}: {v}")

    lines.extend(["", "## Next actions (top 3 from open items)"])
    items = oi.get("items", [])[:3] if isinstance(oi.get("items"), list) else []
    for item in items:
        sev = item.get("severity", "info")
        title = item.get("title", "")[:80]
        lines.append(f"- [{sev}] {title}")

    # Cap at 100 lines
    return "\n".join(lines[:100]) + "\n"


def _resolve_state_dir() -> Path:
    sys.path.insert(0, str(_REPO_ROOT / "scripts" / "lib"))
    try:
        from vnx_paths import resolve_paths
        return Path(resolve_paths()["VNX_STATE_DIR"])
    except Exception:
        return _REPO_ROOT / ".vnx-data" / "state"


def write_project_status(state_dir: Path | None = None) -> Path:
    """Write PROJECT_STATUS.md atomically. Returns path written."""
    content = build_project_status(state_dir)
    state_dir = state_dir or _resolve_state_dir()
    target = state_dir / "PROJECT_STATUS.md"
    tmp = target.with_suffix(".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(target)
    return target


if __name__ == "__main__":
    path = write_project_status()
    print(f"PROJECT_STATUS.md written: {path}")
