#!/usr/bin/env python3
"""Generate docs/core/DAEMON_LIVENESS.md (D2).

Reads scripts/lib/daemon_register.py — the single source of truth for which
processes VNX's supervisor actually starts (parsed from
vnx_supervisor_simple.sh's start_all(), not a hand-kept list) — and renders
its current liveness measurement as a table. Generation over editing: this
table is a snapshot of a live measurement, so it goes stale the moment
someone hand-edits it instead of re-running this script.

This is a DEDICATED file, not a section spliced into docs/core/SUBSYSTEMS.md:
that ledger's `subsystems-drift` CI check (scripts/check_subsystems_drift.py)
parses every 5-cell markdown table row in the file as a cockpit-subsystem
row, with no table-boundary awareness. A "daemon | script(s) | conditional |
state | since" table also has 5 cells, so splicing it into SUBSYSTEMS.md
made the drift check fail on every daemon (reproduced while building this
script: `make subsystems-check` -> exit 1, all nine daemons reported as
phantom rows). Daemons are OS processes; SUBSYSTEMS.md's rows are feature
flags -- a genuinely different register (overlap: exactly two, measured in
the D2 dispatch) that happens to share a table shape. Keeping them in
separate files removes the collision instead of special-casing the checker
for a coincidence.

Usage:
    python3 scripts/generate_daemon_liveness_md.py
    python3 scripts/generate_daemon_liveness_md.py --check   # exit 1 on drift
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

_SCRIPT_DIR = Path(__file__).resolve().parent
_LIB_DIR = _SCRIPT_DIR / "lib"
if str(_LIB_DIR) not in sys.path:
    sys.path.insert(0, str(_LIB_DIR))

import project_root  # noqa: E402
from daemon_register import measure_daemon_liveness, read_daemon_register  # noqa: E402

_BEGIN_MARKER = "<!-- BEGIN generated: scripts/generate_daemon_liveness_md.py -->"
_END_MARKER = "<!-- END generated: scripts/generate_daemon_liveness_md.py -->"


def render_table() -> str:
    register = read_daemon_register()
    liveness = measure_daemon_liveness(register)
    daemons = liveness.get("daemons", {})

    lines = [
        _BEGIN_MARKER,
        "",
        "# VNX Daemon Liveness",
        "",
        "Generated by `python3 scripts/generate_daemon_liveness_md.py` from "
        "`scripts/lib/daemon_register.py`, which parses `start_all()` in "
        "`scripts/vnx_supervisor_simple.sh` — the sole source of truth for "
        "which processes VNX's supervisor starts (three other candidate "
        "registers were rejected as derived duplicates or a different "
        "register entirely; see the module docstring). A snapshot of a live "
        "psutil measurement at generation time, not a live view — re-run "
        "the script for current state. See `docs/core/SUBSYSTEMS.md` for "
        "the separate cockpit-subsystem ledger (feature flags, not "
        "processes).",
        "",
        f"Overall: **{liveness.get('overall', 'unknown')}**",
        "",
        "| daemon | script(s) | conditional | state | since |",
        "|---|---|---|---|---|",
    ]
    for spec in register:
        entry = daemons.get(spec.name, {})
        scripts = ", ".join(f"`{s}`" for s in spec.scripts)
        conditional = "yes" if spec.conditional else "no"
        state = entry.get("state", "unknown")
        since = entry.get("since") or "—"
        lines.append(f"| `{spec.name}` | {scripts} | {conditional} | {state} | {since} |")
    lines.append("")
    lines.append(_END_MARKER)
    return "\n".join(lines) + "\n"


def _apply(check: bool) -> int:
    doc_path = project_root.resolve_project_root(__file__) / "docs" / "core" / "DAEMON_LIVENESS.md"
    text = doc_path.read_text(encoding="utf-8") if doc_path.exists() else ""
    new_block = render_table()

    if _BEGIN_MARKER in text and _END_MARKER in text:
        start = text.index(_BEGIN_MARKER)
        end = text.index(_END_MARKER) + len(_END_MARKER)
        updated = text[:start] + new_block.rstrip("\n") + text[end:]
    elif text:
        sep = "" if text.endswith("\n\n") else ("\n" if text.endswith("\n") else "\n\n")
        updated = text + sep + new_block
    else:
        updated = new_block

    if check:
        if updated != text:
            print(f"DRIFT: {doc_path} is stale relative to the daemon register.", file=sys.stderr)
            return 1
        return 0

    doc_path.parent.mkdir(parents=True, exist_ok=True)
    doc_path.write_text(updated, encoding="utf-8")
    print(f"wrote {doc_path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 on drift instead of writing")
    args = parser.parse_args()
    return _apply(check=args.check)


if __name__ == "__main__":
    sys.exit(main())
